apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-postgres-0
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: "/mnt/data"
